#!/bin/bash
#
# Run NLP flask server
#
# Clean, build and start server


# Stop on errors, print commands
# See https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -Eeuo pipefail
# set -x


# Stuff to run Flask server
# export FLASK_ENV=development
# FLASK_ENV=development
export FLASK_APP=__init__.py
#flask run --no-reload --host 0.0.0.0 --port 8003
flask run --host 0.0.0.0 --port 8003